const users = [
  {
    name: "Julia Young",
    nickname: "julia.young",
    email: "julia.young@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Wendy Diaz",
    nickname: "wendy.diaz",
    email: "wendy.diaz@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Aaron Watson",
    nickname: "aaron.watson",
    email: "aaron.watson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "George Long",
    nickname: "george.long",
    email: "george.long@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Quincy White",
    nickname: "quincy.white",
    email: "quincy.white@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Fiona Adams",
    nickname: "fiona.adams",
    email: "fiona.adams@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Bob Murphy",
    nickname: "bob.murphy",
    email: "bob.murphy@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Zach Howard",
    nickname: "zach.howard",
    email: "zach.howard@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Vince Howard",
    nickname: "vince.howard",
    email: "vince.howard@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Kevin Johnson",
    nickname: "kevin.johnson",
    email: "kevin.johnson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Rachel Davis",
    nickname: "rachel.davis",
    email: "rachel.davis@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Rachel Howard",
    nickname: "rachel.howard",
    email: "rachel.howard@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Victor Bryant",
    nickname: "victor.bryant",
    email: "victor.bryant@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Oscar Diaz",
    nickname: "oscar.diaz",
    email: "oscar.diaz@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Bob Ortiz",
    nickname: "bob.ortiz",
    email: "bob.ortiz@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Wendy Cooper",
    nickname: "wendy.cooper",
    email: "wendy.cooper@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Alice Ward",
    nickname: "alice.ward",
    email: "alice.ward@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Oscar Murphy",
    nickname: "oscar.murphy",
    email: "oscar.murphy@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Tracy Moore",
    nickname: "tracy.moore",
    email: "tracy.moore@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Quincy Allen",
    nickname: "quincy.allen",
    email: "quincy.allen@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Ivan Young",
    nickname: "ivan.young",
    email: "ivan.young@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Rose Moore",
    nickname: "rose.moore",
    email: "rose.moore@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hannah Kelly",
    nickname: "hannah.kelly",
    email: "hannah.kelly@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Zoe Foster",
    nickname: "zoe.foster",
    email: "zoe.foster@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Paula Carter",
    nickname: "paula.carter",
    email: "paula.carter@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Kevin Davis",
    nickname: "kevin.davis",
    email: "kevin.davis@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Gabe Morgan",
    nickname: "gabe.morgan",
    email: "gabe.morgan@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Wendy Moore",
    nickname: "wendy.moore",
    email: "wendy.moore@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hannah Johnson",
    nickname: "hannah.johnson",
    email: "hannah.johnson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Fiona Perez",
    nickname: "fiona.perez",
    email: "fiona.perez@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Kyle Murphy",
    nickname: "kyle.murphy",
    email: "kyle.murphy@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Ian Evans",
    nickname: "ian.evans",
    email: "ian.evans@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Michael Long",
    nickname: "michael.long",
    email: "michael.long@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Fiona Long",
    nickname: "fiona.long",
    email: "fiona.long@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Sam Kelly",
    nickname: "sam.kelly",
    email: "sam.kelly@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hannah Baker",
    nickname: "hannah.baker",
    email: "hannah.baker@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Carl Hughes",
    nickname: "carl.hughes",
    email: "carl.hughes@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Mark King",
    nickname: "mark.king",
    email: "mark.king@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Owen Russell",
    nickname: "owen.russell",
    email: "owen.russell@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Alice Watson",
    nickname: "alice.watson",
    email: "alice.watson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Wendy Kelly",
    nickname: "wendy.kelly",
    email: "wendy.kelly@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Charlie Cooper",
    nickname: "charlie.cooper",
    email: "charlie.cooper@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Dana Adams",
    nickname: "dana.adams",
    email: "dana.adams@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Zach Nelson",
    nickname: "zach.nelson",
    email: "zach.nelson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Charlie Bell",
    nickname: "charlie.bell",
    email: "charlie.bell@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Edward Cox",
    nickname: "edward.cox",
    email: "edward.cox@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Owen Wilson",
    nickname: "owen.wilson",
    email: "owen.wilson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Julia Martin",
    nickname: "julia.martin",
    email: "julia.martin@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Michael Murphy",
    nickname: "michael.murphy",
    email: "michael.murphy@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Julia Rivera",
    nickname: "julia.rivera",
    email: "julia.rivera@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hope Reed",
    nickname: "hope.reed",
    email: "hope.reed@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Tracy Morgan",
    nickname: "tracy.morgan",
    email: "tracy.morgan@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Aaron Diaz",
    nickname: "aaron.diaz",
    email: "aaron.diaz@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hope Bryant",
    nickname: "hope.bryant",
    email: "hope.bryant@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Ian Reed",
    nickname: "ian.reed",
    email: "ian.reed@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Charlie Young",
    nickname: "charlie.young",
    email: "charlie.young@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Quincy Ortiz",
    nickname: "quincy.ortiz",
    email: "quincy.ortiz@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Lily Johnson",
    nickname: "lily.johnson",
    email: "lily.johnson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Will Martin",
    nickname: "will.martin",
    email: "will.martin@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Julia Nelson",
    nickname: "julia.nelson",
    email: "julia.nelson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hannah Watson",
    nickname: "hannah.watson",
    email: "hannah.watson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Vince Baker",
    nickname: "vince.baker",
    email: "vince.baker@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Vince Smith",
    nickname: "vince.smith",
    email: "vince.smith@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Michael Kelly",
    nickname: "michael.kelly",
    email: "michael.kelly@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Zoe Ortiz",
    nickname: "zoe.ortiz",
    email: "zoe.ortiz@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Victor Torres",
    nickname: "victor.torres",
    email: "victor.torres@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Vince Murphy",
    nickname: "vince.murphy",
    email: "vince.murphy@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Ian Price",
    nickname: "ian.price",
    email: "ian.price@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Vince Lopez",
    nickname: "vince.lopez",
    email: "vince.lopez@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Jade Hughes",
    nickname: "jade.hughes",
    email: "jade.hughes@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Ivan Moore",
    nickname: "ivan.moore",
    email: "ivan.moore@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hope King",
    nickname: "hope.king",
    email: "hope.king@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Mark Kelly",
    nickname: "mark.kelly",
    email: "mark.kelly@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Dana Scott",
    nickname: "dana.scott",
    email: "dana.scott@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Zoe Scott",
    nickname: "zoe.scott",
    email: "zoe.scott@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Owen Bryant",
    nickname: "owen.bryant",
    email: "owen.bryant@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Eli Lopez",
    nickname: "eli.lopez",
    email: "eli.lopez@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hope Johnson",
    nickname: "hope.johnson",
    email: "hope.johnson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Zoe Allen",
    nickname: "zoe.allen",
    email: "zoe.allen@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Nina Allen",
    nickname: "nina.allen",
    email: "nina.allen@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hannah Lopez",
    nickname: "hannah.lopez",
    email: "hannah.lopez@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Lily Davis",
    nickname: "lily.davis",
    email: "lily.davis@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Quinn James",
    nickname: "quinn.james",
    email: "quinn.james@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Lily Cox",
    nickname: "lily.cox",
    email: "lily.cox@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Paula Gomez",
    nickname: "paula.gomez",
    email: "paula.gomez@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Rose Ortiz",
    nickname: "rose.ortiz",
    email: "rose.ortiz@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Aaron Clark",
    nickname: "aaron.clark",
    email: "aaron.clark@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Pam Reed",
    nickname: "pam.reed",
    email: "pam.reed@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Tina Russell",
    nickname: "tina.russell",
    email: "tina.russell@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Carl Ortiz",
    nickname: "carl.ortiz",
    email: "carl.ortiz@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Aaron Bryant",
    nickname: "aaron.bryant",
    email: "aaron.bryant@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "George Price",
    nickname: "george.price",
    email: "george.price@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Diana Cooper",
    nickname: "diana.cooper",
    email: "diana.cooper@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Lily Foster",
    nickname: "lily.foster",
    email: "lily.foster@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Mark James",
    nickname: "mark.james",
    email: "mark.james@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Zach Young",
    nickname: "zach.young",
    email: "zach.young@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Hannah Lewis",
    nickname: "hannah.lewis",
    email: "hannah.lewis@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Xavier Turner",
    nickname: "xavier.turner",
    email: "xavier.turner@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Wendy Watson",
    nickname: "wendy.watson",
    email: "wendy.watson@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
  {
    name: "Michael James",
    nickname: "michael.james",
    email: "michael.james@example.com",
    password: "test1234",
    passwordConfirm: "test1234",
  },
];

export { users };
